name: Deploy, Load Test, and Report

on:
  workflow_dispatch:  

jobs:
  ecs-deploy-and-test:
    runs-on: ubuntu-latest
    env:
      CLUSTER: ${{ secrets.ECS_CLUSTER }}
      SERVICE: ${{ secrets.ECS_SERVICE }}
      APP_URL: ${{ secrets.APP_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --force-new-deployment

      - name: Wait for ECS service tasks to stabilize
        run: |
          aws ecs wait services-stable --cluster "$CLUSTER" --services "$SERVICE"

      # Option 2: Apache Bench
      - name: Install Apache Bench
        run: sudo apt-get install -y apache2-utils

      - name: Run Apache Bench (ab)
        run: ab -n 100 -c 10 "$APP_URL" > ab_results.txt

      - name: Report results in summary
        run: |
          echo "### k6 Load Test Results" >> $GITHUB_STEP_SUMMARY
          tail -20 k6_results.txt >> $GITHUB_STEP_SUMMARY
          echo "\n### Apache Bench Results" >> $GITHUB_STEP_SUMMARY
          grep "Requests per second\|Time per request\|Failed requests" ab_results.txt >> $GITHUB_STEP_SUMMARY
