name: Rotate AWS Credentials

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 3 1 * *' # Monthly at 3am UTC

jobs:
  rotate-aws-credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install boto3 requests pynacl

      - name: Show active AWS Access Key ID
        run: echo "Access Key
