name: Deploy

on:
  workflow_dispatch:

jobs:
  configure-and-call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read deployment config from JSON
        id: config
        run: |
          CPU=$(jq -r .cpu .github/deployment-config.json)
          MEMORY=$(jq -r .memory .github/deployment-config.json)
          echo "cpu=$CPU" >> $GITHUB_OUTPUT
          echo "memory=$MEMORY" >> $GITHUB_OUTPUT

      - name: Debug outputs
        run: |
          echo "CPU set to ${{ steps.config.outputs.cpu }}"
          echo "Memory set to ${{ steps.config.outputs.memory }}"

    # Call the reusable workflow, passing the config as inputs
    outputs:
      cpu: ${{ steps.config.outputs.cpu }}
      memory: ${{ steps.config.outputs.memory }}

  call-reusable:
    needs: configure-and-call
    uses: your-org/your-repo/.github/workflows/config-reusable-deploy.yml@main
    with:
      cpu: ${{ needs.configure-and-call.outputs.cpu }}
      memory: ${{ needs.configure-and-call.outputs.memory }}

