name: ECS Deploy Test Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy job executed"

  email_notify_success:
    needs: deploy
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success email job would run here"

  email_notify_failure:
    needs: deploy
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Failure email job would run here"
