name: Deploy image to ECS

on:
  push:
    tags:
      - 'v*'

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: myappservice
  ECS_CLUSTER: doc-cluster
  ECS_SERVICE: doc-task-service
  TASK_DEFINITION_FAMILY: doc-task
  CONTAINER_NAME: doc-task
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    # ... your deployment steps (unchanged) ...

  email_notify_success:
    needs: deploy
    if: ${{ success() }}
    # ... notification steps (unchanged) ...

  email_notify_failure:
    needs: deploy
    if: ${{ failure() }}
    # ... notification steps (unchanged) ...

  rollback:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: your-org/your-repo/.github/workflows/ecs-rollback.yml@main
    with:
      previous_image_tag: "your-old-image-tag"    # SET THIS MANUALLY!
      aws_region: "ap-south-1"
      ecs_cluster: "doc-cluster"
      ecs_service: "doc-task-service"
      container_name: "doc-task"
      task_definition_family: "doc-task"
