# Code Generated by Sidekick is for learning and experimentation purposes only.
# Use official Node.js LTS as the base image for build stage
FROM node:20-alpine as build

WORKDIR /app

# Install dependencies efficiently using package.json, package-lock.json
COPY package*.json ./
RUN npm ci --only=production

# Copy application source files
COPY . .

# Optional: build step, e.g. for React/TypeScript (uncomment if needed)
# RUN npm run build

################################################################################
# Production image: copy built app into a clean environment, drop privileges
FROM node:20-alpine as prod

WORKDIR /app

# Copy only what's needed for production
COPY --from=build /app /app

# Use a non-root user for security
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 3000   # CHANGE this if your app runs on a different port

# Start the application
CMD ["npm", "start"]
