name: ECS Blue/Green Deploy

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      cluster:
        required: true
        type: string
      service:
        required: true
        type: string
      task-definition-arn:
        required: true
        type: string
            secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}

      - name: Update ECS Service (Blue/Green)
        run: |
          aws ecs update-service \
            --cluster ${{ inputs.cluster }} \
            --service ${{ inputs.service }} \
            --force-new-deployment \
            --task-definition ${{ inputs.task-definition-arn }}
            
