name: Grype Vulnerability Scan for ECR Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'ECR image to scan (example: 792394825386.dkr.ecr.ap-south-1.amazonaws.com/myappservice:4c2d68a297768e178f8d0182368ad6da865ca3c6)'
        required: true
        default: '792394825386.dkr.ecr.ap-south-1.amazonaws.com/myappservice:latest'

jobs:
  grype-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo (optional, useful for audit/logging)
      - name: Checkout repo
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Authenticate to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 792394825386.dkr.ecr.${AWS_REGION}.amazonaws.com

      # Install Grype
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # Scan image for vulnerabilities
      - name: Scan ECR image with Grype
        run: grype ${{ github.event.inputs.image }} --fail-on high --output table
