name: Grype Vulnerability Scan for ECR Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'ECR image to scan (e.g., 792394825386.dkr.ecr.ap-south-1.amazonaws.com/myappservice:latest)'
        required: true
        default: '792394825386.dkr.ecr.ap-south-1.amazonaws.com/myappservice:latest'

jobs:
  grype-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout (optional)
      - name: Checkout repo
        uses: actions/checkout@v3

      # Install AWS CLI using official script (works on Ubuntu Noble)
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Authenticate to ECR
      - name: Authenticate to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region "$AWS_REGION" | \
            docker login --username AWS --password-stdin 792394825386.dkr.ecr.$AWS_REGION.amazonaws.com

      # Install Grype
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # Scan image for vulnerabilities (fail if high severity found)
      - name: Scan ECR image with Grype
        run: grype ${{ github.event.inputs.image }} --fail-on high --output table
