name: Build and Deploy Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build artifact (simulate build)
        run: |
          mkdir out
          echo "This is a deployment artifact" > out/artifact.txt
          echo "Sample log" > build.log

      - name: Generate version/tag output (simulate)
        id: set_tag
        run: echo "image_tag=build-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artifact
          path: out/

      - name: Upload build log (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-artifact
          path: ./deploy-artifact

      - name: Download build log (optional)
        uses: actions/download-artifact@v4
        with:
          name: build-log
          path: .

      - name: Use workflow output
        run: |
          echo "Deploying with image tag: ${{ needs.build.outputs.image_tag }}"
          cat ./deploy-artifact/artifact.txt
          cat build.log
